services:
  llamara:
    image: ghcr.io/llamara-ai/llamara:main # latest distribution snapshot
    # image: ghcr.io/llamara-ai/llamara-backend:latest # latest backend release
    # image: docker.io/llamara-ai/llamara-backend-jvm # locally build image
    hostname: llamara
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio_init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    environment:
      # shared with other services in this stack
      - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - QUARKUS_MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - QUARKUS_MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - QUARKUS_REDIS_CHAT_MEMORY_PASSWORD=${REDIS_PASSWORD}
      - QUARKUS_REDIS_CHAT_HISTORY_PASSWORD=${REDIS_PASSWORD}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      # additional environment variables
      - QUARKUS_OIDC_CREDENTIALS_SECRET=${QUARKUS_OIDC_CREDENTIALS_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  postgres:
    image: postgres:17
    hostname: postgres
    networks:
      - internal
    # ports:
    #   - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=llamara
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=llamara
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U llamara -d llamara" ]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    hostname: minio
    networks:
      - internal
    command: server /data --console-address ":9001"
    ports:
    #   - 9000:9000 # MinIO server
     - 9001:9001 # MinIO console
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=llamara
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3

  minio_init:
    image: minio/mc:RELEASE.2025-02-08T19-14-21Z
    networks:
      - internal
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc admin accesskey create myminio --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY} --name llamara-backend;
      exit 0;
      "

  redis:
    image: redis:7.4
    hostname: redis
    networks:
      - internal
    command: redis-server --save 60 1 --loglevel notice --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis_data:/data
    #  - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  qdrant:
    image: qdrant/qdrant:v1.13.3
    hostname: qdrant
    networks:
      - internal
    ports:
      - 6333:6333 # REST API & web interface
    #  - 6334:6334 # gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  internal:
    external: false
