services:
  llamara:
    image: ghcr.io/llamara-ai/llamara:latest # latest distribution release
    # image: docker.io/llamara-ai/llamara-backend-jvm # locally build backend image
    hostname: llamara
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio_init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    env_file: .app.env

  postgres:
    image: postgres:17
    hostname: postgres
    networks:
      - internal
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U llamara -d llamara" ]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    hostname: minio
    networks:
      - internal
    command: server /data --console-address ":9001"
    # ports:
    #   - 9000:9000 # MinIO server
    #   - 9001:9001 # MinIO console
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=llamara
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3

  minio_init:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    networks:
      - internal
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc admin accesskey create myminio --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY} --name llamara-backend;
      exit 0;
      "

  redis:
    image: redis:7.4
    hostname: redis
    networks:
      - internal
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  qdrant:
    image: qdrant/qdrant:v1.13.4
    hostname: qdrant
    networks:
      - internal
    # ports:
    #   - 6333:6333 # REST API & web interface
    #   - 6334:6334 # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  internal:
    external: false

volumes:
  postgres_data:
  minio_data:
  redis_data:
  qdrant_data:
